import { useState } from 'react';
import { Brain, Search } from 'lucide-react';
import InsightCard from '../components/InsightCard';
import { MOCK_INSIGHTS } from '../mockData';

const FILTERS = [
  { id: 'all', label: 'All Types' },
  { id: 'positive', label: 'Positive' },
  { id: 'risk', label: 'Risks' },
  { id: 'opportunity', label: 'Opportunities' },
  { id: 'pattern', label: 'Patterns' },
];

export default function ParentInsights() {
  const [filter, setFilter] = useState('all');

  const filtered =
    filter === 'all'
      ? MOCK_INSIGHTS
      : MOCK_INSIGHTS.filter((i) => i.type === filter);

  return (
    <div className="space-y-6 pb-24">
      {/* Header */}
      <div>
        <div className="flex items-center gap-2 mb-1">
          <Brain className="h-4 w-4 text-slate-400" />
          <p className="text-[10px] uppercase tracking-[0.3em] text-slate-500">Generated by Monty</p>
        </div>
        <h1 className="font-display text-xl font-semibold text-ink sm:text-2xl">AI Insights</h1>
      </div>

      {/* Filters */}
      <div className="flex gap-2 overflow-x-auto pb-1 -mx-1 px-1">
        {FILTERS.map((f) => (
          <button
            key={f.id}
            onClick={() => setFilter(f.id)}
            className={`rounded-full px-3 py-1.5 text-[11px] font-semibold uppercase tracking-[0.15em] whitespace-nowrap transition ${
              filter === f.id
                ? 'bg-ink text-mist shadow-lift'
                : 'border border-ink/20 text-ink hover:border-ink/40'
            }`}
          >
            {f.label}
          </button>
        ))}
      </div>

      {/* Insights List */}
      <div className="space-y-3">
        {filtered.length > 0 ? (
          filtered.map((insight, i) => (
            <InsightCard key={insight.id} insight={insight} index={i} />
          ))
        ) : (
          <div className="flex flex-col items-center justify-center py-16 text-slate-400">
            <Search className="h-8 w-8 mb-3 text-slate-300" />
            <p className="text-sm text-slate-500">No insights of this type yet</p>
          </div>
        )}
      </div>
    </div>
  );
}
